parameters:
  app.log_file_path: 'log/oe_consistency_check.log'
  app.export_directory_path: 'export'
  app.unused_seo_urls_file: 'Unused-Seo-Urls'
  app.duplicate_seo_urls_file: 'Duplicate-Seo-Urls'

imports:
  - { resource: src/ImageManager/services.yaml }
  - { resource: src/Shared/services.yaml }
  - { resource: src/Export/services.yaml }
  - { resource: src/SeoUrl/services.yaml }
  - { resource: src/ExportByFilter/services.yaml }

services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\ConsistencyCheck\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true
