services:
  # Product Image Entities
  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC1:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $column: 'OXPIC1'
      $directory: 'pictures/master/products/1'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC2:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC2'
      $directory: 'pictures/master/products/2'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC3:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC3'
      $directory: 'pictures/master/products/3'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC4:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC4'
      $directory: 'pictures/master/products/4'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC5:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC5'
      $directory: 'pictures/master/products/5'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC6:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC6'
      $directory: 'pictures/master/products/6'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC7:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC7'
      $directory: 'pictures/master/products/7'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC8:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC8'
      $directory: 'pictures/master/products/8'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC9:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC9'
      $directory: 'pictures/master/products/9'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC10:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC10'
      $directory: 'pictures/master/products/10'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC11:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC11'
      $directory: 'pictures/master/products/11'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ProductOXPIC12:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXPIC12'
      $directory: 'pictures/master/products/12'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\OXICON:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXICON'
      $directory: 'pictures/master/products/icon'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\OXTHUMB:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Product'
      $table: 'oxarticles'
      $fieldName: 'OXTHUMB'
      $directory: 'pictures/master/products/thumb'
    tags: ['oe.image_entity']

  # Category Image Entities
  OxidEsales\ConsistencyCheck\Entity\ImageEntity\CategoryOXTHUMB:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Category'
      $table: 'oxcategories'
      $fieldName: 'OXTHUMB'
      $directory: 'pictures/master/category/thumb'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\CategoryOXICON:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Category'
      $table: 'oxcategories'
      $fieldName: 'OXICON'
      $directory: 'pictures/master/category/icon'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\OXPROMOICON:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Category'
      $table: 'oxcategories'
      $fieldName: 'OXPROMOICON'
      $directory: 'pictures/master/category/promo_icon'
    tags: ['oe.image_entity']

  # Manufacturer Image Entities

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ManufacturerOXICON:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Manufacturer'
      $table: 'oxmanufacturers'
      $fieldName: 'OXICON'
      $directory: 'pictures/master/manufacturer/icon'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ManufacturerOXPICTURE:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Manufacturer'
      $table: 'oxmanufacturers'
      $fieldName: 'OXPICTURE'
      $directory: 'pictures/master/manufacturer/picture'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ManufacturerOXPROMOTION_ICON:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Manufacturer'
      $table: 'oxmanufacturers'
      $fieldName: 'OXPROMOTION_ICON'
      $directory: 'pictures/master/manufacturer/promo_icon'
    tags: ['oe.image_entity']

  OxidEsales\ConsistencyCheck\Entity\ImageEntity\ManufacturerOXTHUMBNAIL:
    class: OxidEsales\ConsistencyCheck\Entity\ImageEntity
    arguments:
      $name: 'Manufacturer'
      $table: 'oxmanufacturers'
      $fieldName: 'OXTHUMBNAIL'
      $directory: 'pictures/master/manufacturer/thumb'
    tags: ['oe.image_entity']