imports:
  - { resource: Entity/services.yaml }
  - { resource: Factory/services.yaml }
  - { resource: Repository/services.yaml }
  - { resource: Console/services.yaml }
  - { resource: Utils/services.yaml }
  - { resource: Service/services.yaml }
  - { resource: WebP/services.yaml }