imports:
  - { resource: Entity/services.yaml }

services:
  _defaults:
    public: false
    autowire: true
    bind:
      Symfony\Component\Finder\Finder: '@OxidEsales\ConsistencyCheck\ImageManager\Utils\Finder'

  OxidEsales\ConsistencyCheck\ImageManager\Utils\Finder:
    class: Symfony\Component\Finder\Finder

  OxidEsales\ConsistencyCheck\ImageManager\Utils\FileSystemUtilsInterface:
    class: OxidEsales\ConsistencyCheck\ImageManager\Utils\FileSystemUtils

  OxidEsales\ConsistencyCheck\ImageManager\Factory\ImageDataTypeFactoryInterface:
    class: OxidEsales\ConsistencyCheck\ImageManager\Factory\ImageEntity

  OxidEsales\ConsistencyCheck\ImageManager\Factory\ImageCollectionFactoryInterface:
    class: OxidEsales\ConsistencyCheck\ImageManager\Factory\ImageCollectionFactory

  OxidEsales\ConsistencyCheck\ImageManager\Repository\ImageDirectoryRepository:
    class: OxidEsales\ConsistencyCheck\ImageManager\Repository\ImageDirectoryRepository

  OxidEsales\ConsistencyCheck\ImageManager\Repository\ImageDatabaseRepository:
    class: OxidEsales\ConsistencyCheck\ImageManager\Repository\ImageDatabaseRepository