services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\Export\Factory\CsvReaderFactoryInterface:
    class: OxidEsales\ConsistencyCheck\Export\Factory\CsvReaderFactory

  OxidEsales\ConsistencyCheck\Export\Factory\CsvWriterFactoryInterface:
    class: OxidEsales\ConsistencyCheck\Export\Factory\CsvWriterFactory

  OxidEsales\ConsistencyCheck\Export\Service\ExportFileNameGeneratorInterface:
    class: OxidEsales\ConsistencyCheck\Export\Service\ExportFileNameGenerator
    arguments:
      $exportDirectoryPath: '%app.export_directory_path%'

  OxidEsales\ConsistencyCheck\Export\Service\ExportServiceInterface:
    class: OxidEsales\ConsistencyCheck\Export\Service\CsvExportService

  OxidEsales\ConsistencyCheck\Export\Service\ExportReaderServiceInterface:
    class: OxidEsales\ConsistencyCheck\Export\Service\CsvExportReaderService
