services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\ImageManager\WebP\WebPImageUsageChecker:
    decorates: OxidEsales\ConsistencyCheck\ImageManager\Service\ImageUsageCheckerInterface
    arguments:
      $inner: '@OxidEsales\ConsistencyCheck\ImageManager\WebP\WebPImageUsageChecker.inner'
      $config: '@OxidEsales\Eshop\Core\Config'