services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      OxidEsales\Eshop\Core\Config: '@=service("OxidEsales\\ConsistencyCheck\\Core\\Registry").getConfig()'

  OxidEsales\ConsistencyCheck\SeoUrl\Service\SeoUrlServiceInterface:
    class: OxidEsales\ConsistencyCheck\SeoUrl\Service\SeoUrlService
    public: true

  OxidEsales\ConsistencyCheck\SeoUrl\Service\SeoUrlTableRendererInterface:
    class: OxidEsales\ConsistencyCheck\SeoUrl\Service\SeoUrlTableRenderer
