services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\ExportByFilter\Console\ExportByFilterCommand:
    arguments:
      $logger: '@OxidEsales\ConsistencyCheck\Shared\Infrastructure\Logger'
    tags:
      - { name: 'console.command' }
