services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Factory\UserCredentialArrayFactory: ~

  OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\DeprecatedCredentialsFilter:
    tags: ['oe.consistency_check.export_filter']
    arguments:
      $arrayFactory: '@OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Factory\UserCredentialArrayFactory'

  OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Infrastructure\UserRepositoryInterface:
    class: OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Infrastructure\UserRepository

  OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Factory\UserCredentialDtoFactoryInterface:
    class: OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Factory\UserCredentialDtoFactory

  OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Service\PasswordHashAnalyzerInterface:
    class: OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\Service\PasswordHashAnalyzer
