services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\ExportByFilter\Filter\Credentials\DeprecatedCredentialsFilter:
    tags: ['oe.consistency_check.export_filter']
