imports:
  - { resource: Entity/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlDtoFactory:
    class: OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlDtoFactory

  OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlArrayFactory:
    class: OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlArrayFactory
