imports:
  - { resource: Configuration/services.yaml }
  - { resource: Infrastructure/services.yaml }
  - { resource: Service/services.yaml }
  - { resource: Console/services.yaml }
  - { resource: Factory/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlDtoFactoryInterface:
    class: OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlDtoFactory
    public: true

  OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlArrayFactory:
    class: OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlArrayFactory
