imports:
  - { resource: Console/services.yaml }
  - { resource: Factory/services.yaml }
  - { resource: Filter/Credentials/services.yaml }

services:
  _defaults:
    autowire: true
    public: false
