imports:
  - { resource: Console/services.yaml }
  - { resource: Factory/services.yaml }
  - { resource: Filter/Credentials/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\ExportByFilter\Service\FilterRegistryInterface:
    class: OxidEsales\ConsistencyCheck\ExportByFilter\Service\FilterRegistry
    arguments:
      $filters: !tagged_iterator oe.consistency_check.export_filter
