services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\ExportByFilter\Factory\ExportConfigurationFactoryInterface:
    class: OxidEsales\ConsistencyCheck\ExportByFilter\Factory\ExportConfigurationFactory
