services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\ConsistencyCheck\SeoUrl\Console\CheckUnusedSeoUrlsCommand:
    arguments:
      $configurationFactory: '@OxidEsales\ConsistencyCheck\SeoUrl\Factory\UnusedSeoUrlExportConfigurationFactory'
      $logger: '@OxidEsales\ConsistencyCheck\Shared\Infrastructure\Logger'
    tags:
      - { name: 'console.command', command: 'oe:consistency_check:check-unused-seo-urls' }

  OxidEsales\ConsistencyCheck\SeoUrl\Console\CheckDuplicateSeoUrlsCommand:
    arguments:
      $configurationFactory: '@OxidEsales\ConsistencyCheck\SeoUrl\Factory\DuplicateSeoUrlExportConfigurationFactory'
      $logger: '@OxidEsales\ConsistencyCheck\Shared\Infrastructure\Logger'
    tags:
      - { name: 'console.command', command: 'oe:consistency_check:check-duplicate-seo-urls' }

  OxidEsales\ConsistencyCheck\SeoUrl\Console\DeleteSeoUrlsCommand:
    arguments:
      $readerConfigurationFactory: '@OxidEsales\ConsistencyCheck\SeoUrl\Factory\SeoUrlExportReaderConfigurationFactory'
      $logger: '@OxidEsales\ConsistencyCheck\Shared\Infrastructure\Logger'
    tags:
      - { name: 'console.command', command: 'oe:consistency_check:delete-seo-urls' }
